[versions]
kotlin = "1.6.10"
kotlinx-coroutines = "1.5.2"
kotlinx-serialization = "1.3.0"
androidCompose = "1.2.0-alpha03"
jbCompose = "1.2.0-alpha01-dev606"
exhaustive = "0.1.1"

[libraries]
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-coreNativeMultithreading = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.5.2-native-mt" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-activity = { module = "androidx.activity:activity", version = "1.3.1" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
androidx-core = { module = "androidx.core:core-ktx", version = "1.2.0" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidCompose" }

jetbrains-compose-compiler = { module = "org.jetbrains.compose.compiler:compiler", version.ref = "jbCompose" }
jetbrains-compose-compilerHosted = { module = "org.jetbrains.compose.compiler:compiler-hosted", version.ref = "jbCompose" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version = "7.0.2" }
materialDesign = { module = "com.google.android.material:material", version = "1.4.0" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version = "1.11.0" }
clikt = { module = "com.github.ajalt.clikt:clikt", version = "3.1.0" }
exhaustiveAnnotation = { module = "app.cash.exhaustive:exhaustive-annotation", version.ref = "exhaustive" }
junit = { module = "junit:junit", version = "4.13.1" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.1" }
truth = { module = "com.google.truth:truth", version = "1.1" }
robolectric = { module = "org.robolectric:robolectric", version = "4.5.1" }
