name: build

on:
  pull_request: {}
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init

      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 14

      - run: ./gradlew -p treehouse build dokkaHtmlMultiModule --parallel
      - run: ./gradlew build --parallel

      - run: ./gradlew -p treehouse publish
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'square/treehouse' }}
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs to website
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'square/treehouse' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: treehouse/build/dokka/htmlMultiModule
          TARGET_FOLDER: docs/latest/
          CLEAN: true

  windows-publish:
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'square/treehouse' }}

    needs:
      - build

    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init

      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 14

      - run: ./gradlew -p treehouse publishMingwX64PublicationToMavenRepository
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
