name: Spotless

on:
  issue_comment:
    types:
      - created

jobs:
  run:
    if: github.repository == 'cashapp/redwood' && github.event.issue.pull_request != '' && contains(github.event.comment.body, '/spotless')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 19

      - uses: gradle/gradle-build-action@v2

      - run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: ./gradlew spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v4
